project:
  type: website
    

website:
  title: "SEC-DASH-2025"
  image: "https://github.com/simonkey1/power_bi/blob/master/images/575shots_so.png?raw=true"
  image-alt: "https://github.com/simonkey1/power_bi/blob/master/images/575shots_so.png?raw=true"
  favicon: assets/favicon.ico

format:
  html:
    
    # toc: true
    code-fold: true
    code-overflow: scroll
    theme:
      # Puedes probar con un tema light y uno dark que te gusten,
      # o dejar "default" y "default-dark" como base.
      light: cerulean
      dark: darkly
    dark-mode: true         # Activa el toggle de Quarto  # Tu CSS personalizado
    link-target: _blank
